name = "quem-sou-eu-backend-v4"
main = "worker.js"
compatibility_date = "2024-01-01"

[[durable_objects.bindings]]
name = "SALA_DO"
class_name = "SalaDO"

[[durable_objects.bindings]]
name = "SALA_COMPETITIVA_DO"
class_name = "SalaCompetitivaDO"

[[durable_objects.bindings]]
name = "BancoDadosDO"
class_name = "BancoDadosDO"

[[durable_objects.bindings]]
name = "PontosGlobaisDO"
class_name = "PontosGlobaisDO"

[[durable_objects.bindings]]
name = "BancoDadosPersonagensDO"
class_name = "BancoDadosPersonagensDO"

[[durable_objects.bindings]]
name = "BancoDadosProfeciasDO"
class_name = "BancoDadosProfeciasDO"

[[durable_objects.bindings]]
name = "BancoDadosMimicaDO"
class_name = "BancoDadosMimicaDO"

[[durable_objects.bindings]]
name = "BancoDadosPregacaoDO"
class_name = "BancoDadosPregacaoDO"

[[durable_objects.bindings]]
name = "BancoDadosVerdadeiroFalsoDO"
class_name = "BancoDadosVerdadeiroFalsoDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = [ "SalaDO", "SalaCompetitivaDO", "BancoDadosDO", "PontosGlobaisDO" ]

[[migrations]]
tag = "v2"
new_sqlite_classes = [ "BancoDadosPersonagensDO", "BancoDadosProfeciasDO", "BancoDadosMimicaDO", "BancoDadosPregacaoDO" ]

[[migrations]]
tag = "v3"
new_sqlite_classes = [ "BancoDadosVerdadeiroFalsoDO" ]

[[d1_databases]]
binding = "pingao_personagens"
database_name = "pingao-personagens"
database_id = "ccd79364-9c1f-42c9-9062-9c1f476fce89"

[[d1_databases]]
binding = "pingao_profecias"
database_name = "pingao-profecias"
database_id = "22063ff3-dc59-42f4-b00d-c0401d0bf65b"

[[d1_databases]]
binding = "pingao_mimica"
database_name = "pingao-mimica"
database_id = "5ec25aff-571b-4d65-bd0f-525795d2ea12"

[[d1_databases]]
binding = "pingao_pregacao"
database_name = "pingao-pregacao"
database_id = "3d154848-adb3-4799-94f8-1dd82fdeb7cf"

pages_build_output_dir = "dist-prod"